branch-defaults:
  master:
    environment: classreg-green
  release:
    environment: classreg-blue
deploy:
  artifact: build/libs/crs-rest-service-1.2.2.war
global:
  application_name: classreg
  default_ec2_keyname: classreg
  default_platform: Tomcat 8 Java 8
  default_region: us-west-1
  sc: git
