branch-defaults:
  master:
    environment: classreg-green
  release:
    environment: classreg-blue
deploy:
  artifact: build/libs/crs-rest-service-1.2.1.war
global:
  application_name: classreg
  default_ec2_keyname: classreg
  default_platform: Tomcat 7 Java 7
  default_region: us-west-1
  sc: git
